// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWoPb-p_05suIMj_Pqhq3_CAYQHzpAOvE',
    appId: '1:667351858880:web:d55e072d30ddaa3ae03725',
    messagingSenderId: '667351858880',
    projectId: 'a-i-gen-project-zdn0qt',
    authDomain: 'a-i-gen-project-zdn0qt.firebaseapp.com',
    databaseURL: 'https://a-i-gen-project-zdn0qt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'a-i-gen-project-zdn0qt.appspot.com',
    measurementId: 'G-4S1RFDRYP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnODfDOlvr6DMrmmch8jGQmty_UGaGmb4',
    appId: '1:667351858880:android:fe7b1013e0e74e6de03725',
    messagingSenderId: '667351858880',
    projectId: 'a-i-gen-project-zdn0qt',
    databaseURL: 'https://a-i-gen-project-zdn0qt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'a-i-gen-project-zdn0qt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvhZPY4Dw3HZZH_KSsydmAPQ6Z_a7CyBM',
    appId: '1:667351858880:ios:44ddb60e42ee8132e03725',
    messagingSenderId: '667351858880',
    projectId: 'a-i-gen-project-zdn0qt',
    databaseURL: 'https://a-i-gen-project-zdn0qt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'a-i-gen-project-zdn0qt.appspot.com',
    androidClientId: '667351858880-d39s1tnkarps0ngtflbre9cphctrc916.apps.googleusercontent.com',
    iosClientId: '667351858880-i0jfsbap2dg5onq60pv8ooj6bs77dmho.apps.googleusercontent.com',
    iosBundleId: 'company.privateaero.fma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvhZPY4Dw3HZZH_KSsydmAPQ6Z_a7CyBM',
    appId: '1:667351858880:ios:44ddb60e42ee8132e03725',
    messagingSenderId: '667351858880',
    projectId: 'a-i-gen-project-zdn0qt',
    databaseURL: 'https://a-i-gen-project-zdn0qt-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'a-i-gen-project-zdn0qt.appspot.com',
    androidClientId: '667351858880-d39s1tnkarps0ngtflbre9cphctrc916.apps.googleusercontent.com',
    iosClientId: '667351858880-i0jfsbap2dg5onq60pv8ooj6bs77dmho.apps.googleusercontent.com',
    iosBundleId: 'company.privateaero.fma',
  );

}